### ISSUE TITLE
Creator Group

### ISSUE THREAD

**Issue by juhahakala** [dcmi/dc-srap#12]
Proposed DCMI Metadata Terms: http://purl.org/dc/terms/creatorGroup

Label: Creator Group

A project or other established group that has created the resource together. 

Recommended practice is to identify the group with a URI. If this is not possible or feasible, a literal value that identifies the group may be provided. It is also possible to give both the name and the URI.

Subproperty of: Creator (http://purl.org/dc/elements/1.1/creator)
		(http://purl.org/dc/terms/creator)

Note: Use this property for long-standing projects and research groups, especially when the scholarly resource does not contain the names of individual authors, or when the project/research group’s role is prominent in the creation of the scholarly resource. 

-- Discussion -- 

Lack of a standard identifier for projects makes it difficult to provide reliable information. Project home pages are notoriously short-lived. Research activity IDentifier (RaID), currently under development in ISO TC 46/SC 9, may alleviate this problem in the future.

**Comment by HughP** [comment]
In business management, it the norm for projects to be housed within an organizational unit. It seems to me that there would be one of several marc roles available to identify the creator entity. Adding a creatorGroup which is not a publisher, or distributor, or owner, or issuing body seems like a "complexification" of metadata. Maybe I'm missing something. Is there another clear use case?

**Comment by kcoyle** [comment]
Could this simply be a corporate body as an agent? Note that DC Terms doesn't have classes for Person or Corporate Body that could be applied to the Creator. It might be time to consider that. These could be applied to other agents, like rights holders (which are often companies). Or one could use the schema.org/Person or Organization.

**Comment by osma** [comment]
Creator is defined so it can take an Organization shape, and I see a group as a kind of (informal) organization, so I think that's good enough and we don't need another property for this. Closing
