### ISSUE TITLE
Grant number 

### ISSUE THREAD

**Issue by juhahakala** [dcmi/dc-srap#14]
Proposed DCMI Metadata Terms: http://purl.org/dc/terms/grantNumber

Label: Grant Number

An alpha-numeric string identifying the funding grant under which the scholarly resource was written.

Example	<dcterms:grantNumber>1 R01 CA 123456-01A1</dcterms:grantNumber>

-- Discussion -- 

Grant numbers are funder specific (the number above has been assigned by the National Institutes of Health) and their uniqueness cannot be guaranteed. But we can require that whenever a Grant number is provided, the Funder must specified as well.

**Comment by osma** [comment]
Done in #59
