### ISSUE TITLE
SRAP approval process

### ISSUE THREAD

**Issue by tombaker** [dcmi/dc-srap#17]
The current process documents are:

- [Draft process for application profile development and endorsement at DCMI](https://dublincore.org/specifications/process/ ) from July 2020 is the one we developed to guide the process of reviewing and approving SRAP.
- Current [Usage Board process](https://github.com/dcmi/usage/blob/master/usage_board_process.md) from 2018.

DCMI had several process documents in the years 2001 to 2009, notably:
- [Procedure for approval of proposals by DCMI](https://github.com/dcmi/repository/blob/master/2007/approval_process/index.md) from August 2007 - see also on [Wayback Machine](https://web.archive.org/web/20190310130150/http://dublincore.org/documents/approval)
- [DCMI Usage Board Administrative Processes](https://www.dublincore.org/legacy/usage-board-process/) from 2006, written by Diane and Stuart (with my help), which discusses application profiles

**Comment by tombaker** [comment]
The Usage Board experimented with the review of application profiles in circa 2007-2009. Here is a process document from 2006 written by Diane Hillmann and Stuart Sutton (with my help) that discusses application profiles:
- https://github.com/dcmi/usage/blob/master/documents/process/index.md

Ultimately, we reviewed only two application profiles:
- Collection Description in 2007 - https://github.com/dcmi/usage/blob/master/reviews/2007/collections-ap/index.md
- SWAP in 2009 - https://github.com/dcmi/usage/blob/master/reviews/2009/swap/_index.md

At the time of the SWAP review, we were testing Mikael Nilsson's draft [Description Set Profile Constraint Language](https://www.dublincore.org/specifications/dublin-core/dc-dsp/).

**Comment by tombaker** [comment]
The current Usage Board process document is at https://github.com/dcmi/usage/blob/master/usage_board_process.md 

The most recent approval process for specifications is from 2007: https://github.com/dcmi/repository/blob/master/2007/approval_process/index.md

**Comment by juhahakala** [comment]
In the 2nd SWAP WG meeting, we discussed division of work between the Governing Board and the Usage Board. Roughly speaking the former could deal with politics; making the decision that a profile draft will be processed by DCMI, and then in the end approving the profile, once the Usage Board has processed and approved its properties, alongside any other content that involves semantics. 

GB would also be the body to decide if a profile is to be sent to ISO, either via the fast track process or normal standardization process. The latter allows changes to the draft, the former (in principle) does not.

**Comment by juhahakala** [comment]
Draft minutes of the 3rd meeting contain the following description of the profile approval process, based on the discussion in the meeting: 

The DCMI Governing Board will accept a draft proposal but
outside of formal DCMI work. The Governing Board will
also give acceptance once the draft has been finalised by
the DCMI Usage Board.

The two DCMI boards have different roles. The DCMI
Governing Board is responsible for political decisions:
approving the development of the suggested profile within
DCMI and, at the end of the process, conferring DCMI
endorsement. Between these milestones, DCMI Usage Board
will process the new and altered properties in the
profile, especially from the semantics point of view.

**Comment by tombaker** [comment]
## DCMI-endorsed application profiles: review and approval processes

Tom Baker, Juha Hakala

Draft 2021-10-30

### Introduction

Much of the perceived value of DCMI Metadata Terms
(DCMI-MT) lies in the generic nature of its properties.
These terms are useful where broad, cross-domain, or
cross-language interoperability is desired.

With the exception of five properties used specifically
for describing learning resources and three properties
for describing collections, which were added between
2001 and 2005, all of the 56 properties defined in
DCMI-MT are of a cross-disciplinary nature.

The notion of "application profile",
which entered Dublin Core discourse [in
1999](http://www.ariadne.ac.uk/issue/25/app-profiles/),
provided a way to keep the DCMI-MT vocabulary relatively
small and generic by providing a context for combining
DCMI-MT properties with properties from other, often
domain-specific, namespaces, or by added constraints
on how properties are used in a specific community or
for a specific application.

In current DCMI practice, application profiles are based
on RDF vocabularies -- vocabularies that conform to the
RDF data model (in which each property is explicitly
associated with an described entity) and have been
published in an RDF serialization syntax. This is the
case even if it is anticipated that a profile may also
be implemented with non-RDF models or encodings (such
as XML or JSON).

The five domain-specific properties that were added
between 2001 and 2005 were approved the DCMI Usage
Board because they filled a gap in an application
profile under development in a DCMI working group.

The process described here aims at striking a balance
between a desire to keep the DCMI-MT vocabulary small
and generic, a need to provide URIs in the DCMI-MT
namespace for properties needed in application profiles
developed by DCMI working groups, and a need to improve
the value proposition for fee-paying institutional
members of DCMI.

According to this process, a DCMI member institution
can propose a draft application profile as a candidate
for endorsement and official publication by DCMI as a
"DCMI-endorsed application profile", to be featured
on the DCMI website and promoted for use in the wider
community.

#### Steps in the process

1. A draft application profile is put forward as a
   candidate for DCMI endorsement by submitting it to the
   Chair of the Governing Board.

2. The proposal to the Governing Board must include an
   initial draft of the profile, which must include:

  - A description of its purpose, scope, domain
    applicability, and intended uses. If more than one
    entity is described (eg, Books and Authors), a domain
    model must be specified.

  - The name of at least one person willing to serve as
    chair of a profile working group.

  - The name of at least one member of the Usage Board
    willing to serve in the working group.

3. To proceed on the endorsement track, the proposal must
   be supported by a simple majority of the Governing
   Board.

4. Once a proposal has the support of the Governing
   Board, the Usage Board is asked to clarify whether it
   can review the profile. This gives the Usage Board an
   opportunity to say if it considers the scope of the
   proposed profile to lie too far outside of its
   expertise or to be semantically irrelevant for
   DCMI-MT. This initial examination of the proposal by 
   the Usage Board will be limited to determining 
   appropriateness and scope and is not expected to 
   address questions of detail.

5. An official DCMI Working Group, tasked with further
   development of the profile draft, is created. This WG
   is supported by DCMI with a public mailing list,
   Github repository, and access to video conferencing.
   Membership in working groups is open to interested 
   members of the public.

6. The working group reviews and edits the draft, with
   discussions and meeting notes posted to the public
   mailing list, Github repository, or Github issue
   tracker.

7. When the draft is deemed mature, it will be posted for
   public comment for at least one month. All substantive
   issues raised will be publicly addressed and resolved.
   The working group may invite the wider community to
   indicate their interest in the draft profile as
   evidence of community demand.

8. Once public review is complete, if a required property
   is not found in existing namespaces, it may be
   proposed by the Working Group to the Usage Board for 
   incorporation into DCMI-MT.

9. Once a draft profile has passed public comment and is
   considered by the working group to be mature enough
   for publication, it will be submitted by the working 
   group to the Usage Board for final review.

10. The Usage Board will review any proposed properties
    and communicate their decisions to the profile
    working group. The Usage Board may ask the working
    group to revise and resubmit a proposed property.

11. Once a draft profile is considered to be ready, with
    all properties defined in namespaces (including
    DCMI-MT), the working group submits the entire
    proposal to the Usage Board for final approval.

12. The Usage Board reviews the draft profile with regard
    to completeness and clarity of documentation. The
    Usage Board may ask the working group to revise and
    resubmit or, if no issues remain to be addressed, it
    approves its publication as a "DCMI-endorsed"
    application profile.

13. Once endorsed, the profile will be published on the
    DCMI website and any terms approved by the Usage
    Board will simultaneously be published in a new
    version of DCMI Metadata Terms.

14. If it is determined, at a future time, that a
    "DCMI-endorsed" profile needs to be updated, the
    process described above will be reactivated to review
    and decide on any proposed changes.

Previous versions 
- 2021-09-14 (Tom Baker, Juha Hakala)
- 2020-07-14 (Paul Walk, Tom Baker)

**Comment by tombaker** [comment]
After UB review, the draft process was reviewed, and approved, by the GB and [has been published](https://www.dublincore.org/specifications/process/) on the DCMI website.

Closing...
