### ISSUE TITLE
Date retracted (proposed new element)

### ISSUE THREAD

**Issue by juhahakala** [dcmi/dc-srap#18]
This is an existing element in FaBiO and could be added to SRAP & DCMIMT as well, possibly with additional date related elements in FaBiO, such as has preprint dissemination date. 

In this case SRAP metadata would serve as a tombstone for something that has been available in the past but has since been retracted. 

Is this FaBiO element used or supported in some applications already?

**Comment by Jashton123** [comment]
For info: in Datacite we have a dateType of 'withdrawn' for retracted material so this would be of interest. We provide guidance to not that it is good practice to include a description that indicates the reason for the retraction or withdrawal.

**Comment by juhahakala** [comment]
I have added to the application profile a comment that the reason for retraction or withdrawal should be provided in Description. Fabio has a separate element for this (http://purl.org/spar/fabio/Retraction) but IMO adding it is not necessary.

**Comment by juhahakala** [comment]
Approved with the following specification: 

Date when the resource was retracted or withdrawn.

Subproperty of: Date http://purl.org/dc/terms/date

Recommended practice is to provide reason for retraction or withdrawal in Description element.

NOTE: Do not use Date lost or Date missing for retracted resources.
