### ISSUE TITLE
URL code repository of a resource.

### ISSUE THREAD

**Issue by freddy-sumba** [dcmi/dc-srap#19]
Sometimes the main descriptions of work are in code repositories like GitHub, which is not the same as the webpage. Inline to reuse/reproduce the work we can express the repository code RUL in the metadata of a resource.

**Comment by osma** [comment]
This is quite similar to relatedDataset property (#9) also proposed for SRAP. It's a link to another resource and how to describe that resource (dataset or code repository) is probably best left out of scope for SRAP.

This is a great suggestion, I think we just need a more formal definition like the one in #9.

**Comment by freddy-sumba** [comment]
It's good, then I think that use DOI is a good Idea for the related dataset.
Thanks.

**Comment by juhahakala** [comment]
A new term for related code set has been added to the profile. It is similar to related dataset, except that it refers to software applications which are relevant to the described resource one way or another.
