### ISSUE TITLE
Depicting SRAP in DCTAP

### ISSUE THREAD

**Issue by tombaker** [dcmi/dc-srap#2]
[DC Tabular Application Profiles](https://github.com/dcmi/dctap/blob/main/TAPprimer.md) is a specification under development by a [DCMI working group](https://www.dublincore.org/groups/application_profiles_ig/). The purpose of DCTAP is to provide semi-formal conventions for representing an application profile in a tabular format (CSV file) - something that a spreadsheet-enabled user could author in Excel (or directly in CSV) and could output to other programs for transformation into a ShEx schema, SHACL graph or other, more formally defined, validation languages.

@kcoyle has drafted a representation of SRAP in the DCTAP format [as a Google Sheet](https://docs.google.com/spreadsheets/d/1fNAw-vRh5qEAWkYyrE-uhKR4iGyGyqYiHymcRe7S1zQ/edit#gid=1163247277).

@osma [suggests](https://lists.dublincore.org/pipermail/dc-srap/2021-June/000004.html) that we try to express SRAP primarily in a format like this, instead of a more free form text document that is not machine-understandable.

I have saved Karen's Google sheet in this repo as [srap.csv](https://github.com/dcmi/dc-srap/blob/main/dctap/srap.csv). Github displays the table nicely, though of course it is rather wide so must be horizontally scrolled.

However, there are other display options. @nishad and I are working on a Python module, [dctap-python](https://github.com/dcmi/dctap-python), the purpose of which is to parse a CSV in DCTAP format, perform some simple quality checks, issue warnings for things that look like errors, and output to stdout in various formats: plain text for human consumption (terse or verbose, with or without warnings), JSON, and YAML.

The module includes a command-line utility for examining a DCTAP CSV in iteractive mode. (In the medium term, the command-line utility may be split out into a separate project that would import from the DCTAP parser.) I have started to document the module, and its behavior, on [dctap-python.readthedocs.io](https://dctap-python.readthedocs.io/en/latest/). Just this week I have been refactoring the Sphinx documentation, which I ported over from the predecessor of this project, [github.com/tombaker/csv2shex](https://github.com/tombaker/csv2shex), so there are plenty of broken links and a few outdated examples from six months ago; I'd like to get this into reasonable shape before summer break.

The advantage of outputting to a format such as text or YAML is that it rotates the wide, horizontal format of the spreadsheet into a vertical format that can more easily be scrolled or printed out. Compare:
- [srap.csv](https://github.com/dcmi/dc-srap/blob/main/dctap/srap.csv)
- [srap.txt](https://github.com/dcmi/dc-srap/blob/main/dctap/srap.txt)
- [srap.yaml](https://github.com/dcmi/dc-srap/blob/main/dctap/srap.yaml)
- [srap.json](https://github.com/dcmi/dc-srap/blob/main/dctap/srap.json)
- [Google sheet](https://docs.google.com/spreadsheets/d/1fNAw-vRh5qEAWkYyrE-uhKR4iGyGyqYiHymcRe7S1zQ/edit#gid=1163247277)
- [Google doc (original)](https://docs.google.com/document/d/1t8y_3fNrf1rATlYohB6LhPPgr7Ltt3e2/edit)

**Comment by juhahakala** [comment]
I support the idea of expressing SRAP first and foremost in a machine readable form such as DCTAP. I have no strong preference as regards which format would be the best for this purpose. In order to discuss questions related to the proposed elements we should establish an issue for each element, as suggested by Karen. Once the problems within an issue have been successfully resolved, description of the element in the DCTAP document can be modified accordingly.
