### ISSUE TITLE
New Date subproperties linked to publication statuses

### ISSUE THREAD

**Issue by juhahakala** [dcmi/dc-srap#20]
"Post mortem" publication statuses should be accompanied with dates, since they represent the end to the date range when the document was available. Therefore there is a need for DateRetracted, DateReplaced, DateMissing and DateLost.

**Comment by osma** [comment]
Copying what @juhahakala posted to the dc-srap list on 2021-10-27:

> New Date type terms (subproperties) needed are:
> * DateReplaced
> * DateRetracted
> * DateMissing
>
> In my opinion, DateMissing does not need to be qualified further to indicate the reason why the resource is missing.
> DateReplaced should only be used in tombstone metadata; i.e. when the previous edition is no longer available at all.
> DateRetracted should be used whenever a resource is retracted; luckily such cases are rare for materials covered by SRAP.
>
> Then we may also need Publication Status Lost and Date type term DateLost.
>
> I would prefer to specify both publication status missing and status lost. It is true that knowing for certain that a digital document has been lost may be difficult, and if so, saying that it is just missing is a better option. However, if there is no doubt, it is better to make it clear that the resource is not just missing, but lost.
>
> For example, documents from disappeared Web sites which blocked robot harvesting are lost, unless they were also made available elsewhere. If reasonable effort cannot locate such copies (or if the former Web site host denies that copies were made), we can safely assume that such documents are lost rather than just missing.  
>
> A stronger argument in favour of publication status lost is that we may be aware of existence of at least one copy (and therefore the publication status of the resource is not missing). But the copy may be unusable either because it cannot be rendered due to the lack of a suitable app (and documentation available to build one), or because the data is unreadable due to media decay or some other reason. A resource may also be available but encrypted, and if the key has been lost, the resource is also as good as lost, especially if the encryption used is strong.  
>
> On the other hand, at least I have thought that SRAP can be applied to printed resources as well. If so, there are plenty of examples of resources which have been lost. For instance, the National Library of Finland burned in 1827, and almost the entire collection of 27.000 items was destroyed. Most of the national collection has been restored over the years, but there are still publications which we know did exist, but have been missing for almost 200 years. After such a long time it is fair to say that we have lost them.

**Comment by kcoyle** [comment]
We need to clarify the definitions of the date properties and on which records each of the statuses belong. For the status terms like "preprint" "accepted" "updated" there seems to be the assumption that these would be only on the metadata for the actual preprint/accepted/updated files. For the three above - date replaced, date retracted, date missing - it is less clear. Let's say if an article is replaced, the newer article would logically be called the "replacement". "Date replaced" would be on the one that has been replaced, but as I understand the meaning, the previous document should no longer exist if it has been replaced.  Is the meaning instead: date that this was issued as a replacement? A document that has been retracted may still exist in one's repository or metadata catalog, so the "date retracted" seems to apply to the version of the article that was retracted. Date missing would go on the metadata record for the document that can no longer be found *at that location*. 

Many of these seem to need links to the related documents - the replaced document, the prior version for updated documents.

**Comment by kcoyle** [comment]
Some more:

dct:isReplacedBy + dct:replaces do not assume that the previous version no longer exists. This really is about superseding versions and previous versions may or may not still exist. If the desire is to assign specific dates to these situations, then I wonder if we can think through if the dates in the records for the previous and replacing versions is sufficient to convey this information. I also wonder if the specific dates are sufficient without the dct:isReplacedBy + dct:replaces terms. What would it mean to say: "dateReplaced" without reference to what it is being replaced by?

**Comment by osma** [comment]
Need to get proposed definitions for these. In particular, it's unclear in the replacement scenario whether the dateReplaced property should be used with the old (replaced) record or with the new one.

**Comment by juhahakala** [comment]
Suggested definitions for proposed dates: 

Karen has 

Date missing

"dateMissing may be used to describe documents that can no longer be found neither with their PIDs nor other URIs provided by the author / publisher. " 

We should avoid the term location in the definition, since, as W3C has made clear, URIs are not locations. 

Date lost

"dateLost may be used to describe documents that have been destroyed, rendered unreadable due to media decay or other technical problems, or which have been missing for a substantial period of time." 

I agree that it may be difficult to know with absolute certainty that something has been lost, but there are nevertheless many examples of lost things. Irene Vallejo's Papyrus is full of examples of such works. 

Date replaced 

"dateReplaced may be used to describe a document that has been replaced with a new document." 

In guidelines we can provide additional guidelines on the use this element. For instance, whether to recommend its usage when changes between the new and old document are not minor, but substantial. An example of major change a Web site that is published with new look and feel & content (but still with the same host organization). The old content is still available in Web archives, but only up to the date dateReplaced date. The National Library of Finland is preparing a MARC Proposal for adding a similar date to MARC 21, although the main role this element will have is to indicate ownership changes with 100 % content drift.

**Comment by juhahakala** [comment]
Further refinements to this initial list may include additional subproperties (although right now I cannot think of anything). It is also necessary to provide guidelines to be included either in DCMI Terms or in the application profile. For instance, guidelines in DCMI Terms may say that dateMissing can be a date range (since by definition if something is only missing, it can be found) but all the other subproperties are just single dates. So if a published document is retracted, datePublished remains unchanged, but dateRetracted is added to the record.   

I

**Comment by juhahakala** [comment]
Juha added draft definitions and usage information to Tom's proposal.

**Comment by kcoyle** [comment]
I'm nervous about the `dataAvailableAsDraft` - If someone sends a friend/colleague a copy of a very early draft, does that become this date? I don't know of any instance that informal, non-public drafts are given a version status for academic purposes. The definition says: "Date(s) when a resource has been made available in the Web or for a limited number of reviewers as a draft." I think this has to be a public draft, not a private one, so I would suggest something like:

*Date when a draft has been made available on the web or in an open repository.*

That, of course, has some overlap with the preprint date, but the difference is the formality of the peer review and the submission for publication. I again look at the documents placed in ArXiv, which are made public but are not necessarily submitted in that form for publication. In fact, I think we could rename this to `dateOfPublicDraft` or something else that implies that this is not the draft submitted for publication, even though the content may be very close to that.

**Comment by juhahakala** [comment]
I have made the changes suggested by Karen. I'll change publication status draft as well, into public draft.

**Comment by osma** [comment]
For the record, here are [Juha's recent changes](https://github.com/dcmi/dc-srap/compare/bc372ffccf036336210a17ad4fc164a6086456af...8c94f550cff1eee1844021b8f3dd8df2a6597690). We can review these in next week's SRAP meeting.

**Comment by juhahakala** [comment]
Date ubproperties agreed in the 14th SRAP WG meeting, May 3rd: 

dateAvailableAsPublicDraft
dateReceivedAsManuscript
dateSubmittedAsPreprint
dateSubmittedAsPostprint
dateAccepted
dateAheadOfPrint
datePublished
dateUpdatedAsPublication
dateRetractedAsPublication
dateMissing
dateLost 

These will be submitted to the Usage Board once the WG has completed the profile.

**Comment by kcoyle** [comment]
I'm sorry I can't make the meetings so I may have missed something. But I'm wondering if the date property(s) is where we want to indicate the version status. This combines two different concepts, and they may not always be available as a single unit. For example, you might know that something is a preprint without having a preprint date. Would it be possible to give the publication status on its own, and have a simple date that is the date of that status. Also, if you don't know the version status, I assume you would use dct:date. It makes sense to me to have something like:
>dct:publicationStatus preprint
>dct:date 2009-12-3

or

>dct:publicationStatus receivedAsManuscript
>dct:date 2009-12-3

**Comment by juhahakala** [comment]
We did not want to allow more than one publication status in a single DC record. It may be confusing to say that a publication has statuses preprint, postprint and publication, even if these statuses have dates attached to them. If only one publication status per record is OK, separate date subproperties for publication statuses can be used to keep track of the timeline of a scholarly resource, from the first public draft.

**Comment by kcoyle** [comment]
@juhahakala I didn't mean to imply that there could be more than one. Those were to be separate examples. I believe we discussed before that there could be two kinds of status information - The status of the article being described; and information about prior status, such as "this published article was accept on (date)". I believe that we decided that the latter would be a note, so that status is to be defined as "the status of this resource being defined". If that is the case, then the date would be the date of this resource with the single status.

**Comment by osma** [comment]
> But I'm wondering if the date property(s) is where we want to indicate the version status. This combines two different concepts, and they may not always be available as a single unit. For example, you might know that something is a preprint without having a preprint date.

In my understanding, this is possible, since the status and the date properties are two different elements. In the case of your example, you could say status=preprint, but without stating anything with the property dateSubmittedAsPreprint.

**Comment by kcoyle** [comment]
But if the status is "preprint" then a date of dateSubmittedAsPreprint is redundant, right? Wouldn't there be need for fewer date types if the dct:date is considered the date of the resource, and "status" gives the status of the resource? What I'm asking is what these date types add that cannot be already said with status?

**Comment by juhahakala** [comment]
Correct. When describing a preprint, there is no need to use dateSubmittedAsPreprint. But when a postprint of the same resource is described, dateSubmittedAsPreprint should be used to specify the past date when the preprint was released. This makes it possible to keep track of the history of the resource. Date element in postprint specifies the release date of postprint. And metadata records describing preprint and postprint may both contain also dateSubmittedAsPublicDraft.

**Comment by kcoyle** [comment]
OK, so this is the opposite of what I remembered. These are NOT dates of the resource version being described but are other dates of note. It will be important to make that very clear in the definitions and any comments.
