### ISSUE TITLE
Relators

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#25]
SRAP suggests using terms from the Library of Congress [list of relators](http://id.loc.gov/vocabulary/relators). The LoC relators are all defined as SKOS Concepts; *some* of the relators are also defined as sub-properties of dc:contributor. 
<img width="343" alt="Screen Shot 2022-10-26 at 6 59 27 AM" src="https://user-images.githubusercontent.com/1564129/198046372-7f7b39f2-08b3-40fd-9e95-23985d5efd3d.png">
Of the terms considered the primary ones for SRAP:

* Editor https://id.loc.gov/vocabulary/relators/edt
* Funder https://id.loc.gov/vocabulary/relators/fnd
* Opponent https://id.loc.gov/vocabulary/relators/opn

only Editor is defined as a property through that sub-property relationship.

While it may be plausible to use defined properties as objects of a triple, it is not clear what the result is in using a SKOS concept as a predicate in a triple.

Note that the KB (Swedish National Library) has created its own version of the LoC list of relators at https://id.kb.se/vocab/role. These are all defined as properties.

**Comment by juhahakala** [comment]
WG has decided to recommend usage of controlled lists of contributor roles. Examples of such lists are MARC Relator codes and unconstrained RDA properties. Local roles should not be used; instead, if there is a need for a new role, an application to register a new relator code should be sent to the Library of Congress.
