### ISSUE TITLE
enumeration (volume, number)

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#28]
For the purposes of identification but also to make FINDING the article itself possible (and assuming that this profile is not limited to digital resources), one needs:

     volume
     number
     pagination

I am assuming that

* the journal title or the title of the proceedings in which the article is a chapter is handled with "dct:isPartOf"
* that pagination is handled with "dct:extent" (which isn't now listed in SRAP)

What remains is having elements for volume and number, which are not covered by DC Terms.

I want to remind you that volume and number is not universal; that there are journals with only one or the other, journals with additional enumeration (Part A, Part B, each with v. and n.), and journals with neither (just a date). However, it is very common for there to be a volume and number and most article metadata has these as elements. 
Depending on how the journal paginates within volumes, the date and pagination alone may not be sufficient find the article.

I don't know how others feel about this, but I also note that with the fields in the SRAP profile it may not be possible to distinguish between an article in a journal and a paper in a conference proceeding. Both the journal title and the conference proceeding book will be entered in "dct:isPartOf". There also will not be a clear distinction between a book and a thesis. This makes me wonder if a "document type" will be necessary for unambiguous access to the resource being described.

Some examples from other metadata schemas [here](https://hackmd.io/KDVoaLa2TVmdNJ5PTm38Cg?view).

**Comment by kcoyle** [comment]
(Reply by Juha)
A possible model is MARC Bibliographic tag 773 (Host item entry, https://www.loc.gov/marc/bibliographic/bd773.html). Enumeration of component parts is provided in 773 subfield $g: 

773 0#$tHorizon$gVol. 17, no. 98 (Feb. 1948), p. 78-159 

In this example, the host item (a serial) is identified by its title in $t. 773 provides many other options as well. For us, such information will be important too.  

In a SRAP record the content of the Host item entry above would be presented as  

 Horizon. Vol. 17, no. 98 (Feb. 1948), p. 78-159.

The title is not unique, so ISSN of the serial should be added. DC Identifier is not appropriate (since it should contain the identifier of the article, not the identifier of the serial in which the article was published): 

Horizon. Vol. 17, no. 98 (Feb. 1948), p. 78-159. ISSN 0262-1223.

If host item information is provided in unstructured form, SRAP or user guide should give examples like the one above about host item information metadata elements and the order in which they should be given.    

We can either provide host item information like title, identifier, enumeration (e.g. volume and number) and pagination in different SRAP terms, or specify a single, MARC tag 773 -like term for this information. I would prefer a single term with nonstructured data, since host item information does not need to be structured. It is easier to provide this metadata as one entity, and user interface developers will also be grateful if all Host item information is available in one place. And it is also easier to specify just one SRAP term, instead of several.     

Whatever we decide to do, MARC 773 gives us a good starting point for planning what kind of information we need to provide about host items relevant to SRAP, such as scientific journals, conference proceedings and monographs.

**Comment by kcoyle** [comment]
@juhahakala Regarding the use of something like MARC 773:

1) There are many different ways to indicate volume and number:
* v.17, n.98
* vol. 17, no. 98
* volume 17, number 98
* 17(98)
* _17_(98)

There are undoubtedly as many different ways to list the date. Some of the SRAP metadata instances will be ingested from other places and will get the data in whatever form that external system uses. There are also differences in how journal titles are recorded, with some systems using an abbreviated title.

The main question, IMO, is whether this data will be only used to display to humans, or if some automated processing, like linking to an article finder system like SFX. 

2) Journal title can be given in `dct:isPartOf` which will isolate that bit of information. The ISSN could be included there, although again that means putting more than one logical data element in a property, which is always problematic.

3) The solution you offer is not quite what `dct:bibliographicCitation` is. It would be the full citation, including author and title of the article. (I'm not convinced of the utility of `dct:bibliographicCitation`.) Perhaps a property called "enumeration" would be better for your solution, although it would be even more appropriate if the journal title information is given in `dct:isPartOf`. 

4) Yet another option would be to put the entire citation in `dct:bibliographicCitation` and treat the other properties as related information for search, and some additional info. The citation could be how the article is cited in the journal or in journal indexes:

`dct:bibliographicCitation`: Hollenbach J, Presbrey J, Berners-Lee T. Using rdf metadata to enable access control on the social semantic web. InProceedings of the Workshop on Collaborative Construction, Management and Linking of Structured Knowledge (CK2009) 2009 Oct 25 (Vol. 514, p. 167).
`dct:creator`: Hollenbach, J
`dct:creator`: Presbrey, J
`dct:creator`: Berners-Lee, T
`dct:title`: Using rdf metadata to enable access control on the social semantic web
`bibo:presentedAt`:Proceedings of the Workshop on Collaborative Construction, Management and Linking of Structured Knowledge (CK2009)
`dct:date`: 2009 Oct 25
`dct:enumeration`: Vol. 514, p. 167

**Comment by kcoyle** [comment]
Some examples of citations, taken from Google Scholar:

1) Aishwarya Kumar, Puneet Kumar Gupta, Ankita Srivastava, A review of modern technologies for tackling COVID-19 pandemic, Diabetes & Metabolic Syndrome: Clinical Research & Reviews, Volume 14, Issue 4, 2020, Pages 569-573, ISSN 1871-4021, https://doi.org/10.1016/j.dsx.2020.05.008.

2) 
![Screenshot 2023-01-28 at 8 12 57 AM](https://user-images.githubusercontent.com/1564129/215277541-81276f89-fbd4-41e2-a832-27bd70d7e27b.png)

3) 
![Screenshot 2023-01-28 at 8 15 09 AM](https://user-images.githubusercontent.com/1564129/215277557-de55acd2-be04-4189-86f3-6bcef21d3d03.png)

**Comment by kcoyle** [comment]
An example from schema.org. Schema has classes for volume and issue and uses them as types.
![Screenshot 2023-01-31 at 6 20 54 AM](https://user-images.githubusercontent.com/1564129/215786349-ee1c4468-57ae-470c-a066-ab9393fd8cb8.png)

**Comment by HughP** [comment]
@kcoyle There is a it of a semantics mis-match here: 

> `bibo:presentedAt`:Proceedings of the Workshop on Collaborative Construction, Management and Linking of Structured Knowledge (CK2009)

my understanding of [bibo:presented](https://web-archive.southampton.ac.uk/neologism.ecs.soton.ac.uk/bibo.html#presentedAt) is that it relates a document to an _Event_. Strictly speaking in the provided example you are relating it to a DCMIType _Colllection_. Therefore it might be better indicated as "isPartOf". If we wanted a DCMIType _Event_ Record for the "Workshop on Collaborative Construction, Management and Linking of Structured Knowledge (CK2009)" we could do that and I think one could use the general relationship in DCMI, or one could use `source` or if one wanted to push the boundaries one could try the semantics of `isVersionOf`.

**Comment by HughP** [comment]
> An example from schema.org. Schema has classes for volume and issue and uses them as types. ![Screenshot 2023-01-31 at 6 20 54 AM](https://user-images.githubusercontent.com/1564129/215786349-ee1c4468-57ae-470c-a066-ab9393fd8cb8.png)

I'm not sure if you are aware of [CSL](https://citationstyles.org/) or not, but you might be interested to take a look at it. There is a whole tool chain around it. And about 67 pieces of software use it. The [entity list is rather detailed.](https://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types)

**Comment by kcoyle** [comment]
@HughP You are correct, I did a sloppy copy/paste there and should have dropped the "proceedings" part of that string. 

I'm not sure what the best solution is for what citations do as "in:" when it isn't "in" a journal. Both BIBO and schema have classes for Chapter, but then there's the whole thing of chapter in a book vs. individually authored piece in a bound volume of pieces (anthology, proceedings). The nice thing about "in:" in a citation is that it avoids having to make that decision. 

The problem with using something like the dct:Event is that the main authors/promoters of SRAP are working in an XML space, so classes don't seem to help much. "event" as a type of resource would work, imo, to describe a conference but not the publications of a conference. So there is still the problem of linking the publication to the event, which is implied in "proceedings." BIBO has "#event:product" which seems to fit. I think that's more complex, though, than desired for SRAP.

**Comment by HughP** [comment]
My impression is that looking at citation formats that publishers use is a fruitless approach. Essentially all materials have a "Matryoshka dolls" arrangement.  This applies to archival materials, journal articles, journal volumes, Books in a series, proceedings, anthologies, etc. Once the inner doll and the outer doll are declared, then it is a matter of translation to the bibliographic formatting required by the publisher. Some bibliographic formatting styles can have as many as 4 dolls in the text. This is where I think the "isPartOf" relationship within a strict DC namespace is useful. But if we are talking about mixing namespaces to find a list of entities required by citation styles then using the CSL entity list or the [BibLaTeX](https://ctan.org/pkg/biblatex?lang=en) list is a fairly pragmatic place to start.

**Comment by osma** [comment]
It turns out that BIBO contains all we need to represent journal article details (volume, issue, number, pageStart, pageEnd) and it has the same two-part structure mentioned in the above comment. This is nicely illustrated in the [journal article example](https://github.com/dcmi/dc-srap/blob/main/docs/examples/journalArticle.md) originally created by Karen - I did some edits and added a visualization as well. There's also another BIBO journal article example (along with examples of applying other bibliographic ontologies) at the bottom of [this 2010 blog post](http://openbiblio.net/2010/09/10/bibliographic-models-in-rdf/index.html).

So I propose that we add the following to the DCTAP profile:

# Scholarly Resource shape

(or possibly a subclass/sub-shape Article or AcademicArticle, following the BIBO type hierarchy)

* bibo:volume
* bibo:issue
* bibo:pageStart
* bibo:pageEnd

# Journal (a new shape)

* dct:title
* bibo:issn
* bibo:eissn

**Comment by HughP** [comment]
With regards the the shape of the journal object...

If the requirement is to reduce or only use one namespace (such as DCT) then using an [ISSN with URN syntax](https://www.issn.org/services/online-services/urn/) allows for the _dct:identifier_ element/property to be used. The difference is where in the property the semantic specificity is indicated.

**Comment by kcoyle** [comment]
@HughP The advantage that I see with bibo:issn is that you do not need to investigate the value to determine what type of identifier it is. dct:identifier is pretty open in terms of values so you have to rummage around looking for "http" and "urn" and "1234". Since this is to be a very journal-heavy vocabulary, the specificity of bibo:issn is a convenience. IMO

**Comment by osma** [comment]
Additions to the TAP in https://github.com/dcmi/dc-srap/issues/28#issuecomment-1889392550 were approved today in SRAP meeting 40. Now we just have to implement this in the CSV file...

Regarding `bibo:issn` vs `dct:identifier`, I agree with Karen; URI values should be opaque and having to parse a value within doesn't feel right. Also, the BIBO ISSN properties make a distinction between `bibo:issn` (presumably the printed ISSN?) and `bibo:eissn` (electronic ISSN), which is not obvious if you only use `dct:identifier` with an ISSN URN. I think that's a good thing because those are often recorded separately.

**Comment by osma** [comment]
@HughP 
> Can you help me better understand how the bibo:ssn/bibo:eissn distinction as an example supports your argument any better than urn:eissn/urn:issn?

Is there such a thing as `urn:eissn`? I can't find any information about it.

Regarding WEMI, I think the rough consensus so far within the SRAP WG has been that it should be agnostic about whether or not to assume a WEMI model, just like Dublin Core doesn't force such distinctions.

Not entirely sure if that answers your question though...

**Comment by osma** [comment]
I just created PR #38 that adds these properties and some guidance to the specification.

I noticed that BIBO defines ISSN properties as having a Literal range, so I changes the examples to use plain literals instead of URNs.
