### ISSUE TITLE
What value(s) should hasPart have?

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#48]
There are no node or value types for "hasPart" in the current TAP. This property is problematic because if it should be anything other than "string" then we would need shapes for a number of possible parts, like journal article, book chapter. This could also be seen as being used to describe embedded datasets or images. 

It may be preferable to remove "hasPart" to avoid that complication.

**Comment by osma** [comment]
I agree - we can consider it out of scope for SRAP and remove it. We already have isPartOf for the other direction. And it's not like we're forbidding the use of hasPart even if we leave it out, it's still in DCTerms if anyone needs to apply it.

**Comment by kcoyle** [comment]
Remove from TAP and from the document

**Comment by kcoyle** [comment]
removed
