### ISSUE TITLE
Embargo date

### ISSUE THREAD

**Issue by juhahakala** [dcmi/dc-srap#5]
Proposed DCMI Metadata Terms: http://purl.org/dc/terms/embargoDate

Label: Embargo Date

The date when the resource will be made publicly available.  

Example	<dcterms:embargoDate>2020-12-31</dcterms:embargoDate>

-- Discussion -- 

Is there a need to say something about the level of specificity required / recommended? 

We do not mention usage of ISO 8601-1, since that is inherited from the Date property. Should this requirement be repeated in SRAP, just in case?

**Comment by kcoyle** [comment]
http://purl.org/spar/fabio/hasEmbargoDate
http://purl.org/spar/fabio/hasEmbargoDuration

The embargo duration may also be useful. At times you know the duration that WILL be used even before a document is published.

**Comment by juhahakala** [comment]
Edited version of Embargo, based on Karen's comment: 

Labels: Embargo Date, Embargo duration

The date when the resource will be made publicly available or embargo duration, when the embargo period will start from the yet unknown publication date.

Examples 
dcterms:<embargoDate>2021-12-31</dcterms:embargoDate>
dcterms:<embargoDuration>6 months</dcterms:embargoDuration>

Is there also a third option: we know that there will be embargo, but we know that embargo will apply, but neither the duration nor the date it ends? This could be encoded e.g. as dcterms:<embargo>Yes</embargo>

**Comment by Jashton123** [comment]
For information: In DataCite we use a dateType of 'available' which would map to dcterms:available.
A date range would be useful (giving dates of start and finish as opposed to simply an embargoDuration which would have to be combined with the embargoDate.
Like the idea of recording that there's an embargo but we don't know anything about it as yet. In DataCite we have a set of values to use for unknown; unvailable; to be announced etc. However, the Yes value would be straightforward.

**Comment by juhahakala** [comment]
Modified proposal for treatment of Embargo, based on discussion in the 3rd meeting of the SRAP WG: 

accessRights is used for saying that there is an access restriction based on embargo. COAR Access Rights vocabulary term embargoed access is the recommended solution for providing this information. The COAR definition of embargoed access is "Embargoed access refers to a resource that is metadata only access until released for open access on a certain date. Embargoes can be required by publishers and funders policies, or set by the author (e.g such as in the case of theses and dissertations)." This is OK for SRAP. 

In addition, SRAP introduces two sub-properties for accessRights, hasEmbargoDate and hasEmbargoDuration. These sub-properties are adopted from FaBiO and allow accurate provision of embargo-related metadata.

**Comment by kcoyle** [comment]
I recall that we discussed dct:available, which is the date in which something becomes available. That could be used for embargo-end-date as well as a publication date. Whether we wish to confound these two is another question - both let people know when something becomes available, but the mechanisms are different and the practical matter of whether one has access could differ.

**Comment by juhahakala** [comment]
I prefer encoding embargo-end-date differently (in a different property) from publication date. Having in the same metadata record two different dates when the resource became/becomes available might cause confusion. If the record is dumbed down, there would be two dc:date elements with different information in them. In practice, embargo-end-date would be provided, and the actual publication date would be lost.

**Comment by kcoyle** [comment]
Ah, @juhahakala you are correct - we can't have embargo-end-date and publication date be the same property - they are different dates. "Available" sounds right for end of embargo as an English language term. Note, too, that a true publication date can be in the future. This is a bit problematic when using `dct:issued` - which is in the past tense. But would it make sense to use `dct:available` ("Date that the resource became or will become available.") for when the embargo ends, and `dct:issued` ("Date of formal issuance of the resource.") for the publication date? That would leave, then, the question of embargo duration, which potentially could be taken from FaBiO.

**Comment by juhahakala** [comment]
Using dct:available for the embargo end date and dct:issued for the publication date does not pass the dumb down test. They are both sub-properties of dc:date. Systems which conflate dct:available and dct:issued would not be able to process these dates in a meaningful way. A possible solution for this problem is to make dct:available a sub-property of dc:rights. Then we would need to decide whether hasEmbargoDate were still needed, since it is more accurate than dct:available.

**Comment by kcoyle** [comment]
Isn't this also the case for embargo date? It will be a date, logically a subproperty of dct:date and dc:date. I don't think there's much we can or should do for people who dumb down all subproperties to dct:date.

**Comment by juhahakala** [comment]
Modified proposal for treatment of Embargo, based on discussion in the 4th meeting of the SRAP WG:

accessRights is used for saying that there is an access restriction based on embargo. COAR Access Rights vocabulary term "embargoed access" is the recommended solution for providing this information. The COAR definition of embargoed access is "Embargoed access refers to a resource that is metadata only access until released for open access on a certain date. Embargoes can be required by publishers and funders policies, or set by the author (e.g such as in the case of theses and dissertations)." This broad definition is acceptable for SRAP, although it does not explicitly cover cases when embargo is based on law.

In addition, SRAP introduces one sub-property for accessRights, EmbargoDate. Data provided will be ISO 8601-1 -encoded date range, which may be open ended. Examples:

2021-01/2021-12-31
/2021-12-31
2021/

End date/time, if known, should be specified as accurately as possible.  

Use of FaBiO properties hasEmbargoDate and hasEmbargoDuration has been considered, but their semantics differs from SRAP embargoDate. FaBiO hasEmbargoDate does not allow date ranges, and the date provided should be the end date. hasEmbargoDuration enables encoding of the embargo period (e.g. 6 months) which is redundant from SRAP point of view, since embargo period can be calculated from date ranges in embargoDuration, provided that they are not open ended.

**Comment by osma** [comment]
This proposal was posted by Alasdair to the dc-srap list on 2021-08-20:

Term Name: embargoDateRange

URI	http://purl.org/dc/terms/embargoDateRange

Label	Embargo Date Range

Definition	A period of time during which the resource is under embargo

Comment	Embargo Date Range may be used to express the temporal range during which the resource is under embargo at any level of granularity. Recommended practice is to express the period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If an exact date is unknown, an approximate (yyyy-mm-dd~) or uncertain date (yyyy-mm-dd?) may be used. If the full date is unknown, month and year (yyyy-mm) or just year (yyyy) may be used. Date ranges may be specified using ISO 8601 period of time specification, in which start and end dates are separated by a '/' (slash) character. If either the start date or end date is missing, dates are recorded as ‘to date’, preceded by a '/' (slash) character (/yyyy-mm-dd) or ‘date from’, followed by a '/' (slash) character (yyyy-mm-dd/).

Type of Term	Property

Has Range	http://www.w3.org/2000/01/rdf-schema#Literal

Subproperty of
Date (http://purl.org/dc/elements/1.1/date)
Date (http://purl.org/dc/terms/date)

**Comment by juhahakala** [comment]
Based on subsequent discussion in the WG I have made a simplified version of Alasdair's proposal. This specification minimizes replication of information provided in DC Metadata Terms Date property specification. 

Embargo Date Range may be used to express the temporal range during which the resource is under embargo. Recommended practice is to express the date range according to the Extended Date/Time Format Specification [EDTF], which defines a fully compliant subset of ISO 8601:2019. The start date of the range may be omitted (e.g. /YYYY-MM-DD). The end date should be provided in full. If an exact date is unknown, an approximate (yyyy-mm-dd~) or uncertain date (yyyy-mm-dd?) may be used.
