### ISSUE TITLE
Grant shape

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#56]
SRAP has grant number as a property. RIOXX has grant with grant_name and grant_id. Given that the grant number may not be known or may not make clear who the funder is, at Aug 13 meeting we discussed having a grant shape with the name of the funder and the ID of the grant.

**Comment by osma** [comment]
Looks good, except I would capitalize the shape name Grant to be consistent with the other shapes.

Can you implement this in the TAP? A pull request maybe?

**Comment by osma** [comment]
Here is the proposed structure discussed at SRAP meeting 51:

```
@prefix ex:     <http://example.org/>.
@prefix srap:     <http://example.org/srap/>.
@prefix dct:    <http://purl.org/dc/terms/>.
@prefix schema: <http://schema.org/>.

# based on Rioxx example:
#
#    <rioxxterms:grant
#            funder_name="Engineering and Physical Sciences Research Council"
#            funder_id="https://ror.org/0439y7842">
#        EP/P010288/1
#    </rioxxterms:grant>

ex:doc1 schema:funding ex:grant1 .

ex:grant1 a schema:Grant ;
  schema:funder "Engineering and Physical Sciences Research Council" ;
  schema:identifier "EP/P010288/1".

ex:doc2 schema:funding ex:grant2 .

ex:grant2 a schema:Grant ; schema:funder ex:org ; schema:identifier "EP/P010288/1".

ex:org schema:name "Engineering and Physical Sciences Research Council" ;
  dct:identifier "https://ror.org/0439y7842" .
```

Here's how it looks in an RDF Sketch diagram:

![image](https://github.com/user-attachments/assets/11a6d111-4c6d-4dc3-b329-2f113cf93726)
