### ISSUE TITLE
Project identifier

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#57]
Based on [rioxxterms:project](https://rioxx.net/profiles/v3-0-final/#rioxxterms:project) - especially in the sciences, projects are getting standard identifiers called [RAiD handles](https://www.raid.org.au/). Other types of identifiers for projects may exist. 

- Is this needed for SRAP? 
- Would it be an SRAP property?
- Is it always a URI identifier?
- Is there other information about projects that needs to be included (e.g. project title)? 

Note that RAiD includes [many data elements](https://metadata.raid.org/en/latest/)

**Comment by osma** [comment]
My two cents:

>     Is this needed for SRAP?

If we accept as a goal the ability to convert from Rioxx to SRAP without loss (at least in normal, reasonable cases...Rioxx has quite a bit of flexibility), then I think we need to include this in SRAP as well.

>     Would it be an SRAP property?

I think so, unless we find an obvious alternative.

>     Is it always a URI identifier?

I think we could follow Rioxx here and require a URI:

"When present, the rioxxterms:project property MUST contain one project ID, a globally unique persistent identifier that identifies a project. Examples might include:

- a local identifier rendered as a URI
- a [RAiD handle](https://www.raid.org.au/)."

>     Is there other information about projects that needs to be included (e.g. project title)?

Hmm, maybe keep it simple and just have a single property with an URI value, like Rioxx has. Then we don't need to introduce a whole new shape. We could consider the modelling of projects out of scope for SRAP; RaID and other metadata schemas (e.g. schema.org, DataCite?) probably already do this well enough.

**Comment by osma** [comment]
Done in #59, closing
