### ISSUE TITLE
Remove relatedCode relatedDataset

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#58]
Suggested at Aug 13 2024 meeting; remove these, and use dc:relation with the desired SRAP properties, mainly dct:identifier and dct:type with COAR.

**Comment by kcoyle** [comment]
In essence, dct:relation would have a valueShape of "Scholarly Resource" - which means that we need to compress that shapeID to a single string: "ScholarlyResource". With the blank space between the words it becomes two separate values when used in valueShape.

**Comment by osma** [comment]
What would this look like in the TAP table? Am I right that this could be as simple as

|shapeID|propertyID|valueShape|
|---|---|---|
|ScholarlyResource|dct:relation|ScholarlyResource

i.e. basically a loop if you draw this as a diagram.

If we do it like this, is it wrong to claim that the value is always a ScholarlyResource? What if the relationship is, say, to a government or NGO-issued report, a fiction book, or a movie? Are these also "scholarly" enough?

Also, I don't see any way of recommending the use of dct:identifier and dct:type in this pattern. Basically all properties for ScholarlyResource could be used.

Another solution would be to define a distinct shape, say, RelatedResource, like this:

|shapeID|propertyID|valueShape|
|---|---|---|
|ScholarlyResource|dct:relation|RelatedResource
|RelatedResource|dct:identifier|
|RelatedResource|dct:type|

That could be seen as a bit artificial (RelatedResource - related to what?) but having a distinct shape would make it possible to recommend specific properties like dct:identifier and dct:type.

**Comment by kcoyle** [comment]
I am now wondering if SRAP actually implies that everything that is cataloged with it is a scholarly resource. There is no class that states that the items described are scholarly. (I could imagine using openWEMI for this.) And as I recall we discussed but rejected the idea of defining "scholarly". SRAP is convenient for scholarly resources but, as far as I can tell, is not limited to them.

**Comment by osma** [comment]
One way around the slippery issue of what is or isn't "scholarly" would be to rename the ScholarlyResource shape to just Resource. That would be in line with not defining "scholarly", I guess?

**Comment by kcoyle** [comment]
Tom's program that takes in the DCTAP CSV, checks everything, and then outputs JSON or YAML has the concept of a "default shape". If we don't intend to ever use the Scholarly Resource shape as a valueShape we could simply leave off the shapeID and every property up to the first named shapeID would be considered part of the default shape. However, if we want to have a kind of iteration from "dct:relation" to the entirely of SRAP then, yes, there has to be a shapeID that encompasses everything. We could use Resource, I suppose. Then the COAR vocabularies used with dct:type would say what type of resource it is. Note, though, that none of the COAR terms = scholarly resource, so we probably need to look at those again.

**Comment by osma** [comment]
Done in srap.csv
