### ISSUE TITLE
Class for SRAP?

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#60]
While working on the first Rioxx to SRAP example I found myself wanting a class for the main shape, "Scholarly Work" or "SRAP resource." The sub-shapes all give you some idea of what they represent (schema:Person, bibo:book) but there is no class for the main shape. You could say that the value of dct:type is the class, but I don't think it is. The value of dct:type is the genre of the SRAP resource. Having a class for SRAP resource would to some extent connect the shape to SRAP, in the way that you connect an XML to an XSD. I know that this isn't a "normal" RDF feature, but I think it would be useful.

**Comment by osma** [comment]
We just renamed the main shape to SRAPResource but still don't have a class for it.

**Comment by osma** [comment]
We could coin a class in the (hypothetical so far) SRAP namespace could be called `srap:SRAPResource` .

**Comment by osma** [comment]
Suggested implementation in PR #65
