### ISSUE TITLE
Linking to PDFs and other files

### ISSUE THREAD

**Issue by osma** [dcmi/dc-srap#62]
In Rioxx, the metadata record can include links to PDFs and other files that the metadata record is (collectively) describing. For example this (from Rioxx [example 3](https://www.rioxx.net/profiles/v3-0-final/#heading3), which is a preprint) represents a link to the PDF:

```xml
    <dc:relation
            rel="item"
            type="application/pdf"
            coar_version="https://purl.org/coar/version/c_ab4af688f83e57aa"
            coar_type="https://purl.org/coar/resource_type/c_6501"
            deposit_date="2023-03-28"
            resource_exposed_date="2023-03-28"
            access_rights_="https://purl.org/coar/access_right/c_abf2"
            license_ref="https://creativecommons.org/licenses/by-nc-nd/4.0/"">
        https://eprints.gla.ac.uk/217807/7/217807.pdf
    </dc:relation>
```

We need some way to express at least the PDF URL, if not the other metadata that was associated specifically with the file. But this quickly gets philosophical; in some sense, the SRAP Resource is like a Work while the PDF is like a Manifestation.

In principle, at least in Rioxx, a resource may contain more than one file. For example the main article plus an appendix, or Word and PDF versions of the same document. However, none of the four Rioxx examples has more than one file. It's pretty rare in the wild in repositories to have more than one file per resource, but it happens.

**Comment by osma** [comment]
`schema:url` would be one way to link to the PDF: https://schema.org/url

**Comment by kcoyle** [comment]
I suppose the question, then, is whether the URL is enough, or if this requires a shape with URL and mime type or other info. Often, the file suffix (.pdf, .rtf) is sufficient. The next question, as we've discussed before, is if we can assume the "1-to-1" principle - that each metadata description will define one and only one resource. That has been the assumption for the DC Terms (even though those terms may be used in structured metadata with repeatable "shapes"). But SRAP is a profile, not a vocabulary, so 1-to-1 may not be appropriate.

**Comment by osma** [comment]
My two cents on this:

1. I think we could consider describing the target of the URL out of scope for SRAP, just like we do for projects. So it's possible to use properties like `dc:format` on the URL, but we don't need to specify that in SRAP. That way we don't need a separate URL shape.
2. I think we should allow 1-to-N, that is, don't limit the number of values of the URL property, just like we don't currently limit the cardinality of any other properties in SRAP either. So it would be allowed to have two or more URLs for the same SRAPResource; these could be e.g. Word and PDF versions of the same document, or the main document and a separate appendix (possibly in a different format). Again, this would be up to the user of the profile.

**Comment by osma** [comment]
Proposed implementation in PR #66

**Comment by osma** [comment]
@kcoyle I was thinking that using `dc:format` could be done like this:

```
:srap_resource schema:url <https://eprints.gla.ac.uk/217807/7/217807.pdf> .

<https://eprints.gla.ac.uk/217807/7/217807.pdf> dc:format "application/pdf" .
```

However, I think this (using dc:format on the URL resource) should be left out of scope for SRAP.

**Comment by osma** [comment]
Question discussed at SRAP meeting 54: do we need to separate between different types of links, for example:

- landing page in a repository
- table of contents
- file itself (e.g. PDF)

For example in MARC 856 field, 2nd indicator and $3 can be used to indicate more specific link types.
